service: pl-chain-consortium-be

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-south-1
  memorySize: 128
  timeout: 30

functions:
  app:
    handler: app/app.handler
    environment: ${file(env.development.json)}
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
