class Constants {

    static JWT_SECRET = "JWT_SECRET";
    static EMAIL_USER = "EMAIL_USER";
    static EMAIL_PASS = "EMAIL_PASS";
    static PL_CHAIN_BASE_PATH = "PL_CHAIN_BASE_PATH";
    static PL_CHAIN_API_KEY = "PL_CHAIN_API_KEY";
    static PL_CHAIN_WALLET_FACTORY_CONTRACT_ID = "PL_CHAIN_WALLET_FACTORY_CONTRACT_ID";
    static PL_CHAIN_PAYMASTER_CONTRACT_ID = "PL_CHAIN_PAYMASTER_CONTRACT_ID";
    static PL_CHAIN_PROJECT_ID = "PL_CHAIN_PROJECT_ID";
    static PL_CHAIN_CHAIN = "PL_CHAIN_CHAIN";
    static PL_CHAIN_ENCRYPTED_WALLET_KEY = "PL_CHAIN_ENCRYPTED_WALLET_KEY";
    static PL_CHAIN_CONSORTIUM_CONTRACT_ADDRESS = "PL_CHAIN_CONSORTIUM_CONTRACT_ADDRESS";
    static PL_CHAIN_CONSORTIUM_CONTRACT_ID = "PL_CHAIN_CONSORTIUM_CONTRACT_ID";
    static STRIPE_SECRET_KEY = "STRIPE_SECRET_KEY";
    static STRIPE_ENDPOINT_SECRET = "STRIPE_ENDPOINT_SECRET";
    static SQS_ACCESS_KEY_ID = "SQS_ACCESS_KEY_ID"
    static SQS_SECRET_ACCESS_KEY = "SQS_SECRET_ACCESS_KEY";

}

module.exports = Constants;