class Constants {

    static PL_CHAIN_BASE_PATH = "PL_CHAIN_BASE_PATH";
    static PL_CHAIN_API_KEY = "PL_CHAIN_API_KEY";
    static PL_CHAIN_CONTRACT_ID = "PL_CHAIN_CONTRACT_ID";
    static PL_CHAIN_PROJECT_ID = "PL_CHAIN_PROJECT_ID";
    static PL_CHAIN_CHAIN = "PL_CHAIN_CHAIN";
    static PL_CHAIN_ENCRYPTED_WALLET_KEY = "PL_CHAIN_ENCRYPTED_WALLET_KEY";
    static PL_CHAIN_CONSORTIUM_CONTRACT_ADDRESS = "PL_CHAIN_CONSORTIUM_CONTRACT_ADDRESS";
    static PL_CHAIN_CONSORTIUM_CONTRACT_ID = "PL_CHAIN_CONSORTIUM_CONTRACT_ID"
}

module.exports = Constants;